name = "clover678"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"
account_id = "23ed6a2959432f8abf45ab9be29c5332"

[build]
command = "cargo install worker-build && worker-build --release"
